/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  chat: () => import("@/views/chat/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "job-detail": () => import("@/views/job-detail/index.vue"),
  "job-edit": () => import("@/views/job-edit/index.vue"),
  jobs: () => import("@/views/jobs/index.vue"),
  knowledge: () => import("@/views/knowledge/index.vue"),
  portal: () => import("@/views/portal/index.vue"),
  profile_capability: () => import("@/views/profile/capability/index.vue"),
  "resume-import": () => import("@/views/resume-import/index.vue"),
  "resumes-editor": () => import("@/views/resumes-editor/index.vue"),
  "user-settings": () => import("@/views/user-settings/index.vue"),
};
