/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'chat',
    path: '/chat',
    component: 'layout.base$view.chat',
    meta: {
      title: 'chat',
      i18nKey: 'route.chat',
      order: 99
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      hideInMenu: true
    }
  },
  {
    name: 'job-detail',
    path: '/job-detail',
    component: 'layout.base$view.job-detail',
    meta: {
      title: 'job-detail',
      i18nKey: 'route.job-detail',
      hideInMenu: true
    }
  },
  {
    name: 'job-edit',
    path: '/job-edit',
    component: 'layout.base$view.job-edit',
    meta: {
      title: 'job-edit',
      i18nKey: 'route.job-edit',
      hideInMenu: true
    }
  },
  {
    name: 'jobs',
    path: '/jobs',
    component: 'layout.base$view.jobs',
    meta: {
      title: 'jobs',
      i18nKey: 'route.jobs',
      order: 4
    }
  },
  {
    name: 'knowledge',
    path: '/knowledge',
    component: 'layout.base$view.knowledge',
    meta: {
      title: 'knowledge',
      i18nKey: 'route.knowledge',
      order: 98
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'portal',
    path: '/portal',
    component: 'layout.base$view.portal',
    meta: {
      title: 'portal',
      i18nKey: 'route.portal'
    }
  },
  {
    name: 'capability-profile',
    path: '/profile/capability',
    component: 'layout.base$view.capability-profile',
    meta: {
      title: 'capability-profile',
      i18nKey: 'route.profile_capability',
      order: 3
    }
  },
  {
    name: 'resume-import',
    path: '/resume-import',
    component: 'layout.base$view.resume-import',
    meta: {
      title: 'resume-import',
      i18nKey: 'route.resume-import',
      order: 2
    }
  },
  {
    name: 'resumes-editor',
    path: '/resumes-editor',
    component: 'layout.base$view.resumes-editor',
    meta: {
      title: 'resumes-editor',
      i18nKey: 'route.resumes-editor',
      hideInMenu: true
    }
  },
  {
    name: 'user-settings',
    path: '/user-settings',
    component: 'layout.base$view.user-settings',
    meta: {
      title: 'user-settings',
      i18nKey: 'route.user-settings',
      hideInMenu: true
    }
  }
];
