/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      hideInMenu: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'portal',
    path: '/portal',
    component: 'layout.base$view.portal',
    meta: {
      title: 'portal',
      i18nKey: 'route.portal'
    }
  },
  {
    name: 'profile',
    path: '/profile',
    component: 'layout.base',
    meta: {
      title: 'profile',
      i18nKey: 'route.profile'
    },
    children: [
      {
        name: 'profile_career',
        path: '/profile/career',
        component: 'view.profile_career',
        meta: {
          title: 'profile_career',
          i18nKey: 'route.profile_career'
        }
      },
      {
        name: 'profile_education',
        path: '/profile/education',
        component: 'view.profile_education',
        meta: {
          title: 'profile_education',
          i18nKey: 'route.profile_education'
        }
      },
      {
        name: 'profile_project',
        path: '/profile/project',
        component: 'view.profile_project',
        meta: {
          title: 'profile_project',
          i18nKey: 'route.profile_project'
        }
      },
      {
        name: 'profile_skill',
        path: '/profile/skill',
        component: 'view.profile_skill',
        meta: {
          title: 'profile_skill',
          i18nKey: 'route.profile_skill'
        }
      }
    ]
  },
  {
    name: 'resumes',
    path: '/resumes',
    component: 'layout.base$view.resumes',
    meta: {
      title: 'resumes',
      i18nKey: 'route.resumes'
    }
  },
  {
    name: 'resumes-editor',
    path: '/resumes-editor',
    component: 'layout.base$view.resumes-editor',
    meta: {
      title: 'resumes-editor',
      i18nKey: 'route.resumes-editor',
      hideInMenu: true
    }
  }
];
